apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "while true; do echo hi; sleep 10; done" ]
      env:
        - name: LOCATION
          valueFrom:
            secretKeyRef:
              name: yaml-secret
              key: location
        - name: BUSINESS
          valueFrom:
            secretKeyRef:
              name: yaml-secret
              key: business
  restartPolicy: Never